name: music_memory
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # 中華フォント対策
  flutter_localizations:
    sdk: flutter

  # Google Fonts
  google_fonts: ^2.1.0

  cupertino_icons: ^1.0.2
  audioplayers:
  # Firebase関連
  firebase_core: ^1.3.0
  cloud_firestore: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/
